add continuous integration to mkdocs
graze/skeleton-project pull request #25
Opened 2018-08-20 17:38 UTC by h-bragg

- Adds some more documentation
- Adds linting
- Makes documentation documentation

2018-08-22 11:58 UTC, biggianteye requested changes
Great stuff. I like the moving of meta documentation from the `README` to the `docs` directory. This serves the dual purpose of having some documentation and also demonstrating how to structure things for `mkdocs`.

There are a number of small consistency/cleanup things to fix though.

2018-08-22 11:58 UTC, biggianteye commented on docs/index.md
> +git init
Consider moving this section above the Replacement section to get the right sequence of events.

2018-08-22 11:58 UTC, biggianteye commented on docs/index.md
> +> `__package-description__`, `__year__` with their correct values in `README.md`,
Stray angled bracket.

![image](https://user-images.githubusercontent.com/1482649/44458024-cf1e2100-a5fc-11e8-9f0f-9c5bea389b7e.png)

2018-08-22 11:58 UTC, biggianteye commented on docs/index.md
> +Setup [Continous Integration](ci.md) with external services.
Set up

2018-08-22 11:58 UTC, biggianteye commented on docs/index.md
> +Setup [Continous Integration](ci.md) with external services.
Also don't need the capitalisation on continuous integration.

2018-08-22 11:58 UTC, biggianteye commented on mkdocs.yml
> +site_name: Skeleton Project
Don't you want the placeholder any more?

2018-08-22 11:58 UTC, biggianteye commented on docs/ci.md
> +1. [Github Pages](external_services/github_pages.md) Hosts any documentation using github pages.
Minor point: If these are meant to be sentences, then get rid of the capitalisation after the service name. eg.

> Docker Hub is used to store docker images.

If it's supposed to be just description, format it in that way. eg. Adding a colon, removing the "Is" and maintaining the capitalisation.

> Docker Hub: Used to store docker images.

2018-08-22 11:58 UTC, biggianteye commented on docs/ci.md
> +1. [Travis](external_services/travis.md) Is our main continuous intergration pipeline and performs testing and building.
intergration  -> integration

2018-08-22 11:58 UTC, biggianteye commented on docs/ci.md
> +1. [Scrutinizer](external_services/scrutinizer.md) Profiles the code looking for coding standards and other recommendations.
"coding standards" -> "coding standards violations"

2018-08-22 11:58 UTC, biggianteye commented on docs/external_services/docker_hub.md
> +Some projects include a `Dockerfile` that should be deployed to [DockerHub][docker-hub].
DockerHub -> Docker Hub

2018-08-22 11:58 UTC, biggianteye commented on docs/external_services/docker_hub.md
> +            ```
Is it worth adding this to the skeleton?

2018-08-22 11:58 UTC, biggianteye commented on docs/external_services/docker_hub.md
> +    1. Goto `Collaborators`
Go to

2018-08-22 11:58 UTC, biggianteye commented on docs/external_services/docker_hub.md
> +            #!/bin/bash
Use `/bin/sh` by default rather than `/bin/bash` unless you are using bash-specific features. Not strictly essential here, but a good rule of thumb for portability.

2018-08-22 11:58 UTC, biggianteye commented on docs/external_services/github.md
> +    This is for graze only, but I expect this step is frequently forgotten.
Is this needed? There are other places that have graze-specific things, such as the docker hub stuff. If so, this note should be added consistently.

2018-08-22 11:58 UTC, biggianteye commented on docs/external_services/github_pages.md
> +1. Add the token to the travis project.
Are both needed or are they alternatives? For someone who has not done this before, it's a bit ambiguous.

2018-08-22 11:58 UTC, biggianteye commented on docs/external_services/packagist.md
> +[packagist-graze]: https://packagist.org/graze
https://packagist.org/packages/graze

2018-08-22 11:58 UTC, biggianteye commented on docs/external_services/scrutinizer.md
> +# Scrutinzer CI
Scrutinizer

2018-08-22 11:58 UTC, biggianteye commented on docs/external_services/scrutinizer.md
> +We use [Scrutinzer][scrutinizer] for coding standards and quality.
Scrutinizer

2018-08-22 11:58 UTC, biggianteye commented on docs/external_services/scrutinizer.md
> +1. Entry the repository name
Enter

2018-08-22 11:58 UTC, biggianteye commented on docs/external_services/scrutinizer.md
> +1. Ensure tests are not being run
Why? (I assume this is because Travis is being used to run tests, but it would be good to mention it briefly)

2018-08-22 11:58 UTC, biggianteye commented on docs/external_services/scrutinizer.md
> +    1. [graze only] If you do not have permissions, ask a graze/@open-source-team member for access
As before, is the `[graze only]` annotation needed, given that only a member of graze could have done the previous step of adding this project to the organisation?

2018-08-22 11:58 UTC, biggianteye commented on docs/external_services/travis.md
> +# Travis-ci
Travis CI

2018-08-22 11:58 UTC, biggianteye commented on docs/external_services/travis.md
> +We use [Travis-ci][travis] for our open source build pipeline which tests all commits.
Travis CI

2018-08-22 11:58 UTC, biggianteye commented on docs/external_services/travis.md
> +1. visit: [travis: Graze Profile][travis-profile]
visit -> Visit

2018-08-22 11:58 UTC, biggianteye commented on docs/external_services/github_pages.md
> +1. Add the following to the `.travis.yml` file to deploy to github pages. _This is included in the sample file_
The fragment below doesn't match what's in `.travis.yml`. Do you want what's in the documentation to be just representative or the actual required contents?

2018-08-22 11:58 UTC, biggianteye commented on README.md
> +> See: <https://graze.github.io/skeleton-project/ci/> for services to integration with
"to integrate with"

2018-08-22 11:58 UTC, biggianteye commented on docs/index.md
> +# Skeleton Project
Same comment as before on the placeholder.

2018-08-22 11:58 UTC, biggianteye commented on README.md
> +> With some changes based on our preferences. Thanks to them!
This entire block quote is now a duplicate of what's in `dos/index.md`. Would it be better to just reduce this section to just pointing people to that page and then telling them to delete this block once they have set everything up?

2018-08-22 12:15 UTC, h-bragg commented on mkdocs.yml
> +site_name: Skeleton Project
It makes the documentation it self look weird. So not sure...

2018-08-22 12:19 UTC, h-bragg commented on docs/external_services/docker_hub.md
> +            ```
only if you are creating an application instead of a library.

2018-08-22 12:20 UTC, h-bragg commented on docs/external_services/docker_hub.md
> +            #!/bin/bash
true; it did have some bash stuff but I removed it.

2018-08-22 12:21 UTC, h-bragg commented on docs/external_services/github.md
> +    This is for graze only, but I expect this step is frequently forgotten.
I put this here has its the whole page is graze specific, where others are just config.

2018-08-24 15:17 UTC, h-bragg commented on docs/external_services/github_pages.md
> +1. Add the token to the travis project.
Ah no. Only 1 is needed. 
I was confused from where this comment was.

2018-08-28 11:51 UTC, h-bragg commented
@biggianteye think I have covered everything, 

There is the question of the Project Name, but using __Project Name__:

1. Is markdown so it gets turned into bold or something
2. Isn't very helpful when visiting the page without context

2018-08-28 12:28 UTC, biggianteye commented
`docs/external_services/docker_hub.md` still has a couple of instances of "Goto".

2018-08-28 12:28 UTC, biggianteye approved these changes

2018-08-28 12:30 UTC, biggianteye commented
On the one hand, we could use some other notation for placeholders which isn't markdown. On the other hand, this one placeholder is in such a prominent place that it should hopefully be obvious that it's a placeholder and so not worth the effort in changing the placeholder format.

2018-08-28 13:10 UTC, merged